// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Library.Models
{
    public partial class Tbook
    {
        public Tbook()
        {
            Tinventory = new HashSet<Tinventory>();
        }

        public int Isbn { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public string Introduction { get; set; }

        public virtual ICollection<Tinventory> Tinventory { get; set; }
    }
}