// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Library.Models
{
    public partial class TborrowingRecord
    {
        public int BorrowingId { get; set; }
        public int? UserId { get; set; }
        public int? InventoryId { get; set; }
        public DateTime? BorrowingTime { get; set; }
        public DateTime? ReturnTime { get; set; }

        public virtual Tinventory Inventory { get; set; }
        public virtual Tuser User { get; set; }
    }
}