// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Library.Models
{
    public partial class Tinventory
    {
        public Tinventory()
        {
            TborrowingRecord = new HashSet<TborrowingRecord>();
        }

        public int InventoryId { get; set; }
        public int? Isbn { get; set; }
        public DateTime? StoreTime { get; set; }
        public string Status { get; set; }

        public virtual Tbook IsbnNavigation { get; set; }
        public virtual ICollection<TborrowingRecord> TborrowingRecord { get; set; }
    }
}