// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Library.Models
{
    public partial class Tuser
    {
        public Tuser()
        {
            TborrowingRecord = new HashSet<TborrowingRecord>();
        }

        public int UserId { get; set; }
        public int? PhoneNumber { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public DateTime? RegistrationTime { get; set; }
        public DateTime? LastLoginTime { get; set; }
        public string Privilege { get; set; }

        public virtual ICollection<TborrowingRecord> TborrowingRecord { get; set; }
    }
}